/**
 * Sound, synthesised from nothing.
 *
 * WHY NO AUDIO FILES
 *
 * Shipping music would mean shipping a licence question with it, and a few
 * megabytes besides. Everything here is generated by the Web Audio API at run
 * time: the drone, the reverb impulse response, the interface clicks, and the
 * data sonification. That means zero bytes of audio in the repository, no
 * attribution ambiguity, and a soundscape that can respond continuously to
 * where the camera is rather than looping.
 *
 * The palette is deliberately narrow — a slowly drifting harmonic drone tuned
 * to a low fundamental, filtered noise for "space", and short bell tones for
 * events. It is meant to sit under the experience, not to be listened to.
 *
 * AUTOPLAY
 *
 * Browsers require a user gesture before audio can start. Nothing here creates
 * an AudioContext until {@link SoundEngine#unlock} is called from a real click
 * or key press, and the UI shows a one-line prompt until then.
 *
 * @module audio/engine
 */

/** Just-intonation ratios used for the drone's partials. */
const PARTIALS = [1, 1.5, 2, 3, 4.5, 6, 8];

export class SoundEngine {
  constructor() {
    /** @type {AudioContext|null} */
    this.ctx = null;
    this.unlocked = false;
    this.enabled = false;
    /** Mix levels, 0..1. */
    this.levels = { master: 0.5, ambience: 0.6, interface: 0.5, sonification: 0.8 };
    /** @type {GainNode|null} */
    this.master = null;
    this._voices = [];
    this._sonifyStop = null;
  }

  /**
   * Create the audio graph. Must be called from a user gesture.
   * @returns {Promise<boolean>} Whether audio is now available.
   */
  async unlock() {
    if (this.unlocked) return true;
    const Ctx = window.AudioContext || window.webkitAudioContext;
    if (!Ctx) return false;
    try {
      this.ctx = new Ctx({ latencyHint: 'playback' });
      if (this.ctx.state === 'suspended') await this.ctx.resume();

      this.master = this.ctx.createGain();
      this.master.gain.value = 0;

      // A gentle limiter so a burst of sonification events can never clip.
      this.limiter = this.ctx.createDynamicsCompressor();
      this.limiter.threshold.value = -8;
      this.limiter.knee.value = 6;
      this.limiter.ratio.value = 12;
      this.limiter.attack.value = 0.004;
      this.limiter.release.value = 0.25;

      this.reverb = this.ctx.createConvolver();
      this.reverb.buffer = this._makeImpulseResponse(4.5, 2.6);
      this.reverbGain = this.ctx.createGain();
      this.reverbGain.gain.value = 0.32;

      this.dry = this.ctx.createGain();
      this.dry.gain.value = 0.8;

      this.master.connect(this.dry).connect(this.limiter);
      this.master.connect(this.reverb).connect(this.reverbGain).connect(this.limiter);
      this.limiter.connect(this.ctx.destination);

      // A destination other code can tap for recording.
      this.recordTap = this.ctx.createGain();
      this.limiter.connect(this.recordTap);

      this.unlocked = true;
      return true;
    } catch {
      this.ctx = null;
      return false;
    }
  }

  /**
   * Turn the ambience on or off.
   * @param {boolean} on
   */
  async setEnabled(on) {
    if (on && !this.unlocked) {
      const ok = await this.unlock();
      if (!ok) return;
    }
    this.enabled = on;
    if (!this.ctx) return;
    const now = this.ctx.currentTime;
    this.master.gain.cancelScheduledValues(now);
    this.master.gain.setTargetAtTime(on ? this.levels.master : 0, now, 0.6);
    if (on && !this._voices.length) this._startAmbience();
    if (!on) this._stopSonification();
  }

  /**
   * Set a mix level.
   * @param {'master'|'ambience'|'interface'|'sonification'} channel
   * @param {number} value 0..1
   */
  setLevel(channel, value) {
    this.levels[channel] = Math.max(0, Math.min(1, value));
    if (channel === 'master' && this.ctx && this.enabled) {
      this.master.gain.setTargetAtTime(this.levels.master, this.ctx.currentTime, 0.1);
    }
    if (channel === 'ambience' && this._ambienceGain && this.ctx) {
      this._ambienceGain.gain.setTargetAtTime(this.levels.ambience * 0.22, this.ctx.currentTime, 0.3);
    }
  }

  /**
   * Continuous parameters that shape the ambience.
   *
   * The soundscape follows the camera: the fundamental drops as you travel
   * outward (a musical analogue of the growing distance), brightness follows
   * the local sunlight, and the noise bed thickens inside an atmosphere.
   *
   * @param {object} state
   * @param {number} state.distanceAu Camera's distance from the Sun.
   * @param {number} state.irradiance Local sunlight, 1.0 at Earth.
   * @param {number} [state.inAtmosphere] 0..1
   */
  updateAmbience(state) {
    if (!this.ctx || !this._voices.length) return;
    const now = this.ctx.currentTime;
    // Two octaves down from Mercury to the Kuiper Belt.
    const octave = Math.log2(Math.max(state.distanceAu, 0.2) / 0.4) / 6;
    const fundamental = 55 * Math.pow(2, -Math.min(octave, 2));
    const brightness = 300 + 2600 * Math.pow(Math.min(state.irradiance, 4), 0.35);

    for (const v of this._voices) {
      v.osc.frequency.setTargetAtTime(fundamental * v.ratio, now, 1.5);
    }
    this._filter?.frequency.setTargetAtTime(brightness, now, 1.2);
    if (this._noiseGain) {
      this._noiseGain.gain.setTargetAtTime(0.012 + 0.05 * (state.inAtmosphere || 0), now, 0.8);
    }
  }

  /** @private Build the drone and the noise bed. */
  _startAmbience() {
    const ctx = this.ctx;
    const now = ctx.currentTime;

    this._ambienceGain = ctx.createGain();
    this._ambienceGain.gain.value = this.levels.ambience * 0.22;
    this._filter = ctx.createBiquadFilter();
    this._filter.type = 'lowpass';
    this._filter.frequency.value = 1200;
    this._filter.Q.value = 0.6;
    this._ambienceGain.connect(this._filter).connect(this.master);

    for (let i = 0; i < PARTIALS.length; i++) {
      const ratio = PARTIALS[i];
      const osc = ctx.createOscillator();
      osc.type = i === 0 ? 'sine' : 'triangle';
      osc.frequency.value = 55 * ratio;

      const gain = ctx.createGain();
      // Higher partials quieter, following roughly 1/n as a natural spectrum.
      gain.gain.value = 0.5 / (1 + ratio * 1.6);

      // Each partial breathes on its own slow cycle, so the drone never
      // repeats audibly — the periods are mutually irrational.
      const lfo = ctx.createOscillator();
      lfo.frequency.value = 0.017 + i * 0.0113;
      const lfoGain = ctx.createGain();
      lfoGain.gain.value = gain.gain.value * 0.6;
      lfo.connect(lfoGain).connect(gain.gain);

      // A few cents of detune per partial thickens the sound.
      osc.detune.value = (i % 2 ? 1 : -1) * (3 + i * 1.7);

      osc.connect(gain).connect(this._ambienceGain);
      osc.start(now);
      lfo.start(now);
      this._voices.push({ osc, gain, lfo, ratio });
    }

    // Filtered pink-ish noise: the "vacuum" bed.
    const noise = ctx.createBufferSource();
    noise.buffer = this._makeNoiseBuffer(6);
    noise.loop = true;
    const noiseFilter = ctx.createBiquadFilter();
    noiseFilter.type = 'bandpass';
    noiseFilter.frequency.value = 420;
    noiseFilter.Q.value = 0.35;
    this._noiseGain = ctx.createGain();
    this._noiseGain.gain.value = 0.012;
    noise.connect(noiseFilter).connect(this._noiseGain).connect(this.master);
    noise.start(now);
    this._noise = noise;
  }

  /**
   * A short bell tone for interface feedback.
   * @param {object} [opts]
   * @param {number} [opts.frequency=880]
   * @param {number} [opts.duration=0.18]
   * @param {number} [opts.gain=1]
   */
  blip(opts = {}) {
    if (!this.ctx || !this.enabled) return;
    const ctx = this.ctx;
    const now = ctx.currentTime;
    const osc = ctx.createOscillator();
    osc.type = 'sine';
    osc.frequency.value = opts.frequency ?? 880;

    // A second oscillator a twelfth up, decaying faster, gives the transient a
    // struck-metal character without needing an FM chain.
    const shimmer = ctx.createOscillator();
    shimmer.type = 'sine';
    shimmer.frequency.value = (opts.frequency ?? 880) * 3;

    const gain = ctx.createGain();
    const level = 0.16 * this.levels.interface * (opts.gain ?? 1);
    const dur = opts.duration ?? 0.18;
    gain.gain.setValueAtTime(0, now);
    gain.gain.linearRampToValueAtTime(level, now + 0.006);
    gain.gain.exponentialRampToValueAtTime(0.0001, now + dur);

    const shimmerGain = ctx.createGain();
    shimmerGain.gain.setValueAtTime(0, now);
    shimmerGain.gain.linearRampToValueAtTime(level * 0.35, now + 0.004);
    shimmerGain.gain.exponentialRampToValueAtTime(0.0001, now + dur * 0.45);

    osc.connect(gain).connect(this.master);
    shimmer.connect(shimmerGain).connect(this.master);
    osc.start(now);
    shimmer.start(now);
    osc.stop(now + dur + 0.05);
    shimmer.stop(now + dur + 0.05);
  }

  /**
   * Sonify a data series.
   *
   * Values are mapped to pitch on a pentatonic scale — which keeps a fast
   * series listenable rather than atonal — and to loudness, so a solar-flare
   * sequence reads as a melody whose peaks you can hear coming. Timing is
   * scheduled ahead on the audio clock rather than driven by timers, so it does
   * not stutter when the renderer is busy.
   *
   * @param {number[]} values Normalised 0..1.
   * @param {object} [opts]
   * @param {number} [opts.noteMs=140]
   * @param {number} [opts.baseFreq=196] G3.
   * @param {(index:number)=>void} [opts.onNote] Called as each note is heard.
   * @returns {()=>void} Stop function.
   */
  sonify(values, opts = {}) {
    if (!this.ctx || !this.enabled || !values.length) return () => {};
    this._stopSonification();

    const ctx = this.ctx;
    const noteMs = opts.noteMs ?? 140;
    const base = opts.baseFreq ?? 196;
    // Minor pentatonic: no semitone clashes however the data jumps.
    const scale = [0, 3, 5, 7, 10, 12, 15, 17, 19, 22, 24];
    const start = ctx.currentTime + 0.08;
    /** @type {OscillatorNode[]} */
    const scheduled = [];

    values.forEach((raw, i) => {
      const v = Math.max(0, Math.min(1, raw));
      const step = scale[Math.min(scale.length - 1, Math.round(v * (scale.length - 1)))];
      const freq = base * Math.pow(2, step / 12);
      const at = start + (i * noteMs) / 1000;

      const osc = ctx.createOscillator();
      osc.type = v > 0.72 ? 'sawtooth' : 'triangle';
      osc.frequency.value = freq;

      const filter = ctx.createBiquadFilter();
      filter.type = 'lowpass';
      filter.frequency.value = 500 + v * 5200;
      filter.Q.value = 1.2;

      const gain = ctx.createGain();
      const level = (0.05 + 0.15 * v) * this.levels.sonification;
      const dur = (noteMs / 1000) * 1.7;
      gain.gain.setValueAtTime(0, at);
      gain.gain.linearRampToValueAtTime(level, at + 0.012);
      gain.gain.exponentialRampToValueAtTime(0.0001, at + dur);

      osc.connect(filter).connect(gain).connect(this.master);
      osc.start(at);
      osc.stop(at + dur + 0.05);
      scheduled.push(osc);

      if (opts.onNote) {
        const delay = Math.max(0, (at - ctx.currentTime) * 1000);
        setTimeout(() => opts.onNote(i), delay);
      }
    });

    const stop = () => {
      for (const o of scheduled) {
        try {
          o.stop();
        } catch {
          /* already stopped */
        }
      }
    };
    this._sonifyStop = stop;
    return stop;
  }

  /** @private */
  _stopSonification() {
    if (this._sonifyStop) {
      this._sonifyStop();
      this._sonifyStop = null;
    }
  }

  /**
   * Build a decaying-noise impulse response for the convolution reverb.
   *
   * A real IR would be a recording of a real space, which is both a licensing
   * question and a download. Exponentially decaying stereo noise with a gentle
   * low-pass over time is indistinguishable from a plausible large hall for
   * this purpose, and costs four lines.
   * @param {number} seconds
   * @param {number} decay Higher is a faster decay.
   * @returns {AudioBuffer}
   * @private
   */
  _makeImpulseResponse(seconds, decay) {
    const rate = this.ctx.sampleRate;
    const length = Math.floor(rate * seconds);
    const buffer = this.ctx.createBuffer(2, length, rate);
    for (let ch = 0; ch < 2; ch++) {
      const data = buffer.getChannelData(ch);
      let lp = 0;
      for (let i = 0; i < length; i++) {
        const t = i / length;
        const envelope = Math.pow(1 - t, decay);
        const white = Math.random() * 2 - 1;
        // One-pole low-pass that closes as the tail decays, so late
        // reflections are darker — which is what real rooms do.
        lp += (white - lp) * (0.35 - 0.28 * t);
        data[i] = lp * envelope;
      }
    }
    return buffer;
  }

  /**
   * Pink-ish noise via the Voss-McCartney approximation.
   * @param {number} seconds
   * @returns {AudioBuffer}
   * @private
   */
  _makeNoiseBuffer(seconds) {
    const rate = this.ctx.sampleRate;
    const length = Math.floor(rate * seconds);
    const buffer = this.ctx.createBuffer(1, length, rate);
    const data = buffer.getChannelData(0);
    let b0 = 0, b1 = 0, b2 = 0, b3 = 0, b4 = 0, b5 = 0, b6 = 0;
    for (let i = 0; i < length; i++) {
      const white = Math.random() * 2 - 1;
      b0 = 0.99886 * b0 + white * 0.0555179;
      b1 = 0.99332 * b1 + white * 0.0750759;
      b2 = 0.969 * b2 + white * 0.153852;
      b3 = 0.8665 * b3 + white * 0.3104856;
      b4 = 0.55 * b4 + white * 0.5329522;
      b5 = -0.7616 * b5 - white * 0.016898;
      data[i] = (b0 + b1 + b2 + b3 + b4 + b5 + b6 + white * 0.5362) * 0.11;
      b6 = white * 0.115926;
    }
    return buffer;
  }

  /**
   * An audio node suitable for mixing into a MediaRecorder stream.
   * @returns {AudioNode|null}
   */
  getRecordingSource() {
    return this.recordTap || null;
  }

  /** Release everything. */
  dispose() {
    this._stopSonification();
    for (const v of this._voices) {
      try {
        v.osc.stop();
        v.lfo.stop();
      } catch {
        /* already stopped */
      }
    }
    this._voices = [];
    try {
      this._noise?.stop();
    } catch {
      /* already stopped */
    }
    this.ctx?.close();
    this.ctx = null;
    this.unlocked = false;
  }
}
